typography_spectrum: 0.33086
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.3232042172458023
  lightness: 0.25640366156585515
  saturation: 0.8625181477982551
  rhythmicContrast: 0.0005503955762833357
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4715035050176084
analytics:
  google: null
  facebook: null
  twitter: null
name: Applied Opportunities Group
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: The inevitable should be forced vigorously into it
purpose: []
